version: '3'

services:
  redis-alpha:
    image: redis
    restart: always
    container_name: redis-alpha
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
  mysql:
    image: mariadb:10.3.5
    ports:
      - "33060:3306"
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
  rabbitmq:
    image: "rabbitmq:latest"
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - 2181:2181
    admin:
      image: apache/dubbo-admin
      depends_on:
        - zookeeper
      ports:
        - 8090:8080
      environment:
        - admin.registry.address=zookeeper://zookeeper:2181
        - admin.config-center=zookeeper://zookeeper:2181
        - admin.metadata-report.address=zookeeper://zookeeper:2181