spring:
  dubbo:
    application:
      name: service-dubbo-provider
      registry: zookeeper://127.0.0.1:2181
  datasource:
    url: jdbc:mysql://localhost:33060/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    enabled: false
server:
  port: 8081

mybatis:
  mapperLocations: classpath:db/mapper/**/*.xml
  type-aliases-package: